apiVersion: v1
kind: Namespace
metadata:
  name: netledger
  labels:
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: netledger-agent
  namespace: netledger
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: netledger-agent
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: netledger-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: netledger-agent
subjects:
- kind: ServiceAccount
  name: netledger-agent
  namespace: netledger
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: netledger-agent
  namespace: netledger
  labels:
    app.kubernetes.io/component: agent
    app.kubernetes.io/instance: main
    app.kubernetes.io/name: netledger
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: agent
      app.kubernetes.io/instance: main
      app.kubernetes.io/name: netledger
  template:
    metadata:
      labels:
        app.kubernetes.io/component: agent
        app.kubernetes.io/instance: main
        app.kubernetes.io/name: netledger
        redeploy-trigger: t
    spec:
      hostNetwork: true
      hostPID: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: netledger-agent
      containers:
      - name: netledger-agent
        image: netledger-agent:v0.0.10
        imagePullPolicy: IfNotPresent
        args:
        - -server=http://172.18.0.1:8080/write-network-statistics
        # - -server=http://netledger-classifier.netledger.svc.cluster.local./write-network-statistics
        - -serviceCidr=10.96.0.0/16
        - -debug=true
        - -node=$(NODE_NAME)
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          privileged: true
          readOnlyRootFilesystem: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: netledger-classifier
  namespace: netledger
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: netledger-classifier
rules:
- apiGroups: [""]
  resources: ["pods", "nodes", "services"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["discovery.k8s.io"]
  resources: ["endpointslices"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: netledger-classifier
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: netledger-classifier
subjects:
- kind: ServiceAccount
  name: netledger-classifier
  namespace: netledger
---
apiVersion: v1
kind: Service
metadata:
  name: netledger-classifier
  namespace: netledger
  labels:
    app.kubernetes.io/component: classifier
    app.kubernetes.io/instance: main
    app.kubernetes.io/name: netledger
spec:
  selector:
    app.kubernetes.io/component: classifier
    app.kubernetes.io/instance: main
    app.kubernetes.io/name: netledger
  ports:
  - port: 80
    targetPort: 8080
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netledger-classifier
  namespace: netledger
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: classifier
      app.kubernetes.io/instance: main
      app.kubernetes.io/name: netledger
  template:
    metadata:
      labels:
        app.kubernetes.io/component: classifier
        app.kubernetes.io/instance: main
        app.kubernetes.io/name: netledger
    spec:
      serviceAccountName: netledger-classifier
      containers:
      - name: netledger-classifier
        image: netledger-classifer:v0.0.1
        imagePullPolicy: IfNotPresent
        args:
          - -serviceCidr=10.11.0.0/16
        ports:
        - containerPort: 8080
          name: http
